
title: "Panel Ciudadanía Escolar"
---
# Reporte metodológico {-}

El involucramiento político de las y los ciudadanas/os es un requisito fundamental de las democracias modernas, y es justamente su visible erosión lo que se diagnóstica como crisis de legitimidad y representación de las mismas. Al mismo tiempo es evidente una ampliación de los repertorios de participación política, especialmente por parte de los jóvenes. Las respuestas desde las políticas públicas a estos rasgos paradojales, en el primer mundo como en Chile, se han enfocado al sistema educativo, sin considerar suficientemente el problema de las desigualdades de origen que afectan a las capacidades de participación, ni tampoco suficientemente las capacidades de agencia que exhiben las nuevas generaciones. En este marco el presente proyecto se propone investigar la socialización política de las nuevas generaciones, o el proceso y mecanismos de adquisición de unas creencias, conocimientos, actitudes y prácticas para el ejercicio de la ciudadanía, en las dos agencias clave de socialización: la familia y la escuela. La pregunta que articula el conjunto es: *¿En qué medida la escuela es un agente reproductor o mitigador de la transmisión intergeneracional de la desigualdad política familiar?* Su respuesta supone un diseño que aborde en profundidad tanto los efectos como los mecanismos de ambas agencias, desde una perspectiva evaluativa que interroga por los factores que profundizan o mitigan las desigualdades en socialización política. <br>
<br>
Para abordar esta pregunta se llevará cabo un Estudio Panel de Ciudadanía Escolar entre 2019 y 2021, evaluando a una muestra representativa de padres, docentes y estudiantes de enseñanza media. La encuesta tiene como eje la implementación de la Ley de Formación Ciudadana y la consiguiente creación de la asignatura de Formación Ciudadana, que comenzará el año 2019 en enseñanza media. De esta manera, la disponibilidad de información aún no explotada y la contingencia de la implementación de la Ley referida representan una oportunidad histórica para avanzar en la investigación de este tema en el país.

[Diseño Metodológico PACES](https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FImage&psig=AOvVaw25iE5fh04jMBHc_47UwACd&ust=1600883688102000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCID68s2q_esCFQAAAAAdAAAAABAD)


<!--stackedit_data:
eyJoaXN0b3J5IjpbLTIzODY5NDEwNCwtMTY0MzI5MDk2NiwtND
IzMzIwOTksLTE2NDMyOTA5NjYsLTg4MjMxNjU4NSwtMTE5OTQ1
MjA5OV19
-->