---
title: "Panel Ciudadanía Escolar"
subtitle: "Reporte de resultados 2019"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 14pt
mainfont: Palatino
monofont: "Source Code Pro"
monofontoptions: "Scale=0.8"
bibliography: [book.bib, packages.bib, openscience.bib]
biblio-style: apalike
link-citations: yes
---

# Presentación del estudio{-}

El involucramiento político de las y los ciudadanas/os es un requisito fundamental de las democracias modernas, y es justamente su visible erosión lo que se diagnóstica como crisis de legitimidad y representación de las mismas. Al mismo tiempo es evidente una ampliación de los repertorios de participación política, especialmente por parte de los jóvenes. Las respuestas desde las políticas públicas a estos rasgos paradojales, en el primer mundo como en Chile, se han enfocado al sistema educativo, sin considerar suficientemente el problema de las desigualdades de origen que afectan a las capacidades de participación, ni tampoco suficientemente las capacidades de agencia que exhiben las nuevas generaciones. En este marco el presente proyecto se propone investigar la socialización política de las nuevas generaciones, o el proceso y mecanismos de adquisición de unas creencias, conocimientos, actitudes y prácticas para el ejercicio de la ciudadanía, en las dos agencias clave de socialización: la familia y la escuela. La pregunta que articula el conjunto es: *¿En qué medida la escuela es un agente reproductor o mitigador de la transmisión intergeneracional de la desigualdad política familiar?* Su respuesta supone un diseño que aborde en profundidad tanto los efectos como los mecanismos de ambas agencias, desde una perspectiva evaluativa que interroga por los factores que profundizan o mitigan las desigualdades en socialización política.

Estructura del reporte:

**Módulo 1: Conocimiento y formación en la escuela**

Sección 1: Conocimiento cívico<br>
<ul>
  <li>Resultados generales</li>
  <li>Comparación con el estudio ICCS 2009</li>
</ul>
Sección 2: Clima democrático en el aula<br>
<ul>
  <li>Importancia de distintos aspectos en la formación ciudadana</li>
  <li>Quién juega el rol más importante en distintos aspectos de la formación ciudadana</li>
</ul>

**Módulo 2: Actitudes políticas**

Sección 1: Interés en la política y en los problemas sociales<br>
Sección 2: Satisfacción con la democracia y actitudes autoritarias<br>
Sección 3: Confianza en grupos e instituciones<br>

**Módulo 3: Participación**

Sección 1: Participación formal<br>
Sección 2: Participación activista<br>
Sección 3: Participación comunitaria<br>

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
<!--stackedit_data:
eyJoaXN0b3J5IjpbMjEwODI2NTg0MywtMTU3NTk5MjldfQ==
-->